Repository ishLearn/ishLearn, pull requests merged in 2022-06, with the labels that each got.

#126 GitHub Actions to Feature Branch
  .github/workflows/docker-image.yml
  README.md
Labels: bug

#121 Fix Dockerfiles and Docker Compose
  .dockerignore
  .github/workflows/docker-image.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  ishlearn-client/vue.config.js
  package-lock.json
  package.json
  server/index.ts
  server/libs/aws/s3Client.ts
  server/models/Product.ts
  server/utils/Logger.ts
  tsconfig.json
Labels: enhancement

#130 Make Redis connection optional
  .github/workflows/docker-image-preview.yml
  .github/workflows/print-branches-pr.yml
  README.md
  server/models/Product.ts
  server/services/RedisService.ts
Labels: bug, enhancement

#142 Add EmailService
  package-lock.json
  package.json
  server/index.ts
  server/services/EmailService.ts
Labels: enhancement

#137 Added date to Signup form. Now it is possible to register new accounts.
  ishlearn-client/src/services/auth.service.ts
  ishlearn-client/src/views/UserSignUpView.vue
Labels: bug

#139 Editor for md now working
  ishlearn-client/package-lock.json
  ishlearn-client/package.json
  ishlearn-client/src/components/GenericInput.vue
  ishlearn-client/src/main.ts
  ishlearn-client/src/router/index.ts
  ishlearn-client/src/util/inputValidation.ts
  ishlearn-client/src/views/ProjectAdd.vue
Labels: enhancement

#147 Added EmailService and Reset Password backend
  server/index.ts
  server/models/EmailToken.ts
  server/routes/callback.ts
  server/routes/tags.ts
  server/routes/users.ts
  server/services/DBService.ts
  server/services/EmailService.ts
Labels: enhancement

#149 Confirm Email (after change and signup)
  server/controllers/AuthController.ts
  server/models/User.ts
  server/routes/callback.ts
  server/routes/users.ts
  server/services/EmailService.ts
Labels: enhancement

#150 Rearranged imports in index: Reduce startup time
  server/index.ts
  server/routes/products.ts
Labels: bug, enhancement

#151 56 form to add projects
  ishlearn-client/src/components/GenericInput.vue
  ishlearn-client/src/components/MDEditor.vue
  ishlearn-client/src/components/MDPreview.vue
  ishlearn-client/src/views/AboutView.vue
  ishlearn-client/src/views/HomeView.vue
  ishlearn-client/src/views/ProjectAdd.vue
  ishlearn-client/src/views/ProjectDetail.vue
Labels: enhancement

#155 "Add Project"-backend working
  ishlearn-client/src/util/inputValidation.ts
  ishlearn-client/src/views/ProjectAdd.vue
  server/models/Product.ts
  server/routes/auth.ts
  server/routes/products.ts
Labels: bug

#159 Added Download / Upload Description on Product POST
  server/models/Comment.ts
  server/models/Media.ts
  server/models/Product.ts
  server/routes/products.ts
  server/routes/users.ts
Labels: enhancement

#161 Fixed typing and description fetch | Avg Rating Products
  ishlearn-client/.eslintrc.js
  ishlearn-client/src/types/Products.ts
  ishlearn-client/src/util/dateUtils.ts
  ishlearn-client/src/views/ProjectDetail.vue
  server/index.ts
  server/models/Product.ts
  server/services/RedisService.ts
Labels: bug, enhancement

#168 Update AboutUser and UpdateUser
  ishlearn-client/src/components/GenericInput.vue
  ishlearn-client/src/router/index.ts
  ishlearn-client/src/types/Users.ts
  ishlearn-client/src/util/dateUtils.ts
  ishlearn-client/src/views/ProjectDetail.vue
  ishlearn-client/src/views/UserLogoutDummy.vue
  ishlearn-client/src/views/UserProfileView.vue
  ishlearn-client/src/views/UserSignUpView.vue
  ishlearn-client/src/views/UserUpdateView.vue
  package.json
  server/index.ts
  server/models/Media.ts
  server/models/User.ts
  server/routes/users.ts
  server/utils/Logger.ts
Labels: bug, enhancement
