Repository ishLearn/ishLearn, pull requests merged in 2022-07, with the labels that each got.

#174 Upload check with uploadBy working
  ishlearn-client/src/util/getUser.ts
  ishlearn-client/src/views/ProjectDetail.vue
  server/models/Product.ts
  server/routes/products.ts
Labels: bug, enhancement

#178 171 deliver filetype at media request
  .vscode/settings.json
  server/models/Comment.ts
  server/models/Media.ts
  server/models/Product.ts
  server/models/User.ts
  server/routes/files/uploads.ts
  server/services/DBService.ts
Labels: enhancement

#180 Added filetype frontend: direct view and image preview
  ishlearn-client/src/components/FileDisplayIcon.vue
  ishlearn-client/src/components/FilePreviewDownload.vue
  ishlearn-client/src/types/Media.ts
  ishlearn-client/src/views/ProjectDetail.vue
  server/models/Media.ts
  server/routes/files/downloads.ts
Labels: enhancement

#190 Delete Files From project
  .vscode/settings.json
  ishlearn-client/src/components/FilePreviewDownload.vue
  ishlearn-client/src/views/ProjectDetail.vue
  ishlearn-client/src/views/ProjectUpdateView.vue
  server/models/Product.ts
  server/routes/products.ts
  server/services/DBService.ts
Labels: bug, enhancement

#200 Added debounce to search
  ishlearn-client/src/components/SearchField.vue
  ishlearn-client/src/util/debounceThrottle.ts
  ishlearn-client/src/views/ProjectsAllView.vue
Labels: enhancement

#203 Fixed 24h-localStorage refreshToken
  ishlearn-client/src/store/auth.module.ts
Labels: bug

#196 Checkboxes are working now
  ishlearn-client/src/components/GenericInput.vue
  ishlearn-client/src/components/ProductPreview.vue
  ishlearn-client/src/icons/IconEye.vue
  ishlearn-client/src/icons/IconEyeSlash.vue
  ishlearn-client/src/styles/style.css
  ishlearn-client/src/types/Products.ts
  ishlearn-client/src/views/ProjectDetail.vue
  ishlearn-client/src/views/ProjectUpdateView.vue
  ishlearn-client/src/views/ProjectsAllView.vue
Labels: bug

#198 Escape special characters and show products bug fixed
  ishlearn-client/src/store/auth.module.ts
  ishlearn-client/src/types/Products.ts
  ishlearn-client/src/views/ProjectDetail.vue
  ishlearn-client/src/views/ProjectUpdateView.vue
  server/models/Media.ts
  server/models/Product.ts
Labels: bug, enhancement

#206 Added TryCatch for User Auth
  server/middleware/authMiddleware.ts
Labels: bug

#207 Automatically delete outtimed RefreshTokens
  server/index.ts
  server/utils/refreshTokens.ts
Labels: enhancement

#208 Add backend handling for same filename
  .vscode/settings.json
  ishlearn-client/package-lock.json
  ishlearn-client/package.json
  ishlearn-client/src/components/DropZone.vue
  ishlearn-client/src/components/FileDisplayIcon.vue
  ishlearn-client/src/components/FilePreviewDownload.vue
  ishlearn-client/src/components/FilePreviewUpload.vue
  ishlearn-client/src/components/GenericInput.vue
  ishlearn-client/src/components/MDEditor.vue
  ishlearn-client/src/components/MDPreview.vue
  ishlearn-client/src/components/NavBar.vue
  ishlearn-client/src/components/ProductPreview.vue
  ishlearn-client/src/components/SearchField.vue
  ishlearn-client/src/components/SmallForm.vue
  ishlearn-client/src/services/auth.service.ts
  ishlearn-client/src/util/debounceThrottle.ts
  ishlearn-client/src/util/file-uploader.ts
  ishlearn-client/src/util/typeguards.ts
  ishlearn-client/src/views/HomeView.vue
  ishlearn-client/src/views/ProjectAdd.vue
  ishlearn-client/src/views/ProjectDetail.vue
  ishlearn-client/src/views/ProjectUpdateView.vue
  ishlearn-client/src/views/ProjectsAllView.vue
  ishlearn-client/src/views/UserLoginView.vue
  ishlearn-client/src/views/UserLogoutDummy.vue
  ishlearn-client/src/views/UserUpdateView.vue
  server/models/Media.ts
  server/models/User.ts
  server/routes/files/uploads.ts
Labels: bug, enhancement
